-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-05-09 17:40:46 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE Cart CASCADE CONSTRAINTS 
;

DROP TABLE CartItems CASCADE CONSTRAINTS 
;

DROP TABLE Categories CASCADE CONSTRAINTS 
;

DROP TABLE Customer CASCADE CONSTRAINTS 
;

DROP TABLE ProductCategories CASCADE CONSTRAINTS 
;

DROP TABLE Products CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Cart 
    ( 
     CartID     INTEGER  NOT NULL , 
     CreatedAt  DATE , 
     CustomerID INTEGER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX Cart__IDX ON Cart 
    ( 
     CustomerID ASC 
    ) 
;

ALTER TABLE Cart 
    ADD CONSTRAINT Cart_PK PRIMARY KEY ( CartID ) ;

CREATE TABLE CartItems 
    ( 
     Cart_CartID        INTEGER  NOT NULL , 
     Products_ProductID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE CartItems 
    ADD CONSTRAINT CartItems_PK PRIMARY KEY ( Cart_CartID, Products_ProductID ) ;

CREATE TABLE Categories 
    ( 
     CategoryID  INTEGER  NOT NULL , 
     Name        NVARCHAR2 (100)  NOT NULL , 
     Description NVARCHAR2 (250) 
    ) 
;

ALTER TABLE Categories 
    ADD CONSTRAINT Categories_PK PRIMARY KEY ( CategoryID ) ;

ALTER TABLE Categories 
    ADD CONSTRAINT Categories_Name_UN UNIQUE ( Name ) ;

CREATE TABLE Customer 
    ( 
     CustomerID       INTEGER  NOT NULL , 
     FirstName        NVARCHAR2 (50)  NOT NULL , 
     LastName         NVARCHAR2 (50)  NOT NULL , 
     Email            VARCHAR2 (150)  NOT NULL , 
     Password         VARCHAR2 (100)  NOT NULL , 
     PhoneNumber      VARCHAR2 (20) , 
     RegistrationDate DATE 
    ) 
;

ALTER TABLE Customer 
    ADD CONSTRAINT Customer_Emai_CKl 
    CHECK (regexp_like(email, '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}')) 
;

ALTER TABLE Customer 
    ADD CONSTRAINT Customer_PK PRIMARY KEY ( CustomerID ) ;

ALTER TABLE Customer 
    ADD CONSTRAINT Customer_Email_UN UNIQUE ( Email ) ;

ALTER TABLE Customer 
    ADD CONSTRAINT Customer_PhoneNumber_UN UNIQUE ( PhoneNumber ) ;

CREATE TABLE ProductCategories 
    ( 
     Products_ProductID    INTEGER  NOT NULL , 
     Categories_CategoryID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE ProductCategories 
    ADD CONSTRAINT ProductsCategories_PK PRIMARY KEY ( Products_ProductID, Categories_CategoryID ) ;

CREATE TABLE Products 
    ( 
     ProductID     INTEGER  NOT NULL , 
     Name          NVARCHAR2 (250)  NOT NULL , 
     Description   NVARCHAR2 (500) , 
     Price         NUMBER (10,2)  NOT NULL , 
     StockQuantity INTEGER DEFAULT 0  NOT NULL , 
     ImageUrl      VARCHAR2 (500) , 
     Slug          VARCHAR2 (350) , 
     Discount      NUMBER (5,2) DEFAULT 0 , 
     Rating        NUMBER (4,2) DEFAULT 0 
    ) 
;
ALTER TABLE Products
    DROP CONSTRAINT product_stock_ck ;
ALTER TABLE Products 
    ADD CONSTRAINT product_stock_ck 
    CHECK (StockQuantity >= 0) 
;

ALTER TABLE Products 
    ADD CONSTRAINT Product_Discount_ck 
    CHECK (Discount >= 0) 
;

ALTER TABLE Products 
    ADD CONSTRAINT Products_PK PRIMARY KEY ( ProductID ) ;

ALTER TABLE Products 
    ADD CONSTRAINT Products_Name_UN UNIQUE ( Name ) ;

ALTER TABLE Products 
    ADD CONSTRAINT Products_Slug_UN UNIQUE ( Slug ) ;

ALTER TABLE Cart 
    ADD CONSTRAINT Cart_Customer_FK FOREIGN KEY 
    ( 
     CustomerID
    ) 
    REFERENCES Customer 
    ( 
     CustomerID
    ) 
;

ALTER TABLE CartItems 
    ADD CONSTRAINT CartItems_Cart_FK FOREIGN KEY 
    ( 
     Cart_CartID
    ) 
    REFERENCES Cart 
    ( 
     CartID
    ) 
;

ALTER TABLE CartItems 
    ADD CONSTRAINT CartItems_Products_FK FOREIGN KEY 
    ( 
     Products_ProductID
    ) 
    REFERENCES Products 
    ( 
     ProductID
    ) 
;

ALTER TABLE ProductCategories 
    ADD CONSTRAINT ProdCat_Categories_FK FOREIGN KEY 
    ( 
     Categories_CategoryID
    ) 
    REFERENCES Categories 
    ( 
     CategoryID
    ) 
;

ALTER TABLE ProductCategories 
    ADD CONSTRAINT ProdtCat_Products_FK FOREIGN KEY 
    ( 
     Products_ProductID
    ) 
    REFERENCES Products 
    ( 
     ProductID
    ) 
;

CREATE SEQUENCE CartItems_Cart_CartID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER CartItems_Cart_CartID_TRG 
BEFORE INSERT ON CartItems 
FOR EACH ROW 
WHEN (NEW.Cart_CartID IS NULL) 
BEGIN 
    :NEW.Cart_CartID := CartItems_Cart_CartID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE Categories_CategoryID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Categories_CategoryID_TRG 
BEFORE INSERT ON Categories 
FOR EACH ROW 
WHEN (NEW.CategoryID IS NULL) 
BEGIN 
    :NEW.CategoryID := Categories_CategoryID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE Customer_CustomerID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Customer_CustomerID_TRG 
BEFORE INSERT ON Customer 
FOR EACH ROW 
WHEN (NEW.CustomerID IS NULL) 
BEGIN 
    :NEW.CustomerID := Customer_CustomerID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE Products_ProductID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Products_ProductID_TRG 
BEFORE INSERT ON Products 
FOR EACH ROW 
WHEN (NEW.ProductID IS NULL) 
BEGIN 
    :NEW.ProductID := Products_ProductID_SEQ.NEXTVAL; 
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             1
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           4
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          4
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
