-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-05-07 20:48:24 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE Cart CASCADE CONSTRAINTS 
;

DROP TABLE CartItems CASCADE CONSTRAINTS 
;

DROP TABLE Categories CASCADE CONSTRAINTS 
;

DROP TABLE Customer CASCADE CONSTRAINTS 
;

DROP TABLE ProductCategories CASCADE CONSTRAINTS 
;

DROP TABLE Products CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Cart 
    ( 
     CartID     INTEGER  NOT NULL , 
     CreatedAt  DATE , 
     CustomerID INTEGER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX Cart__IDX ON Cart 
    ( 
     CustomerID ASC 
    ) 
;

ALTER TABLE Cart 
    ADD CONSTRAINT Cart_PK PRIMARY KEY ( CartID ) ;

CREATE TABLE CartItems 
    ( 
     Cart_CartID        INTEGER  NOT NULL , 
     Products_ProductID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE CartItems 
    ADD CONSTRAINT CartItems_PK PRIMARY KEY ( Cart_CartID, Products_ProductID ) ;

CREATE TABLE Categories 
    ( 
     CategoryID  INTEGER  NOT NULL , 
     Name        NVARCHAR2 (100)  NOT NULL , 
     Description NVARCHAR2 (250) 
    ) 
;

ALTER TABLE Categories 
    ADD CONSTRAINT Categories_PK PRIMARY KEY ( CategoryID ) ;

CREATE TABLE Customer 
    ( 
     CustomerID       INTEGER  NOT NULL , 
     FirstName        NVARCHAR2 (50)  NOT NULL , 
     LastName         NVARCHAR2 (50)  NOT NULL , 
     Email            VARCHAR2 (150)  NOT NULL , 
     Password         VARCHAR2 (100)  NOT NULL , 
     PhoneNumber      VARCHAR2 (20) , 
     RegistrationDate DATE 
    ) 
;

ALTER TABLE Customer 
    ADD CONSTRAINT Customer_PK PRIMARY KEY ( CustomerID ) ;

CREATE TABLE ProductCategories 
    ( 
     Products_ProductID    INTEGER  NOT NULL , 
     Categories_CategoryID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE ProductCategories 
    ADD CONSTRAINT ProductsCategories_PK PRIMARY KEY ( Products_ProductID, Categories_CategoryID ) ;

CREATE TABLE Products 
    ( 
     ProductID     INTEGER  NOT NULL , 
     Name          NVARCHAR2 (250)  NOT NULL , 
     Description   NVARCHAR2 (500) , 
     Price         NUMBER (10,2)  NOT NULL , 
     StockQuantity INTEGER  NOT NULL , 
     ImageUrl      VARCHAR2 (500) , 
     Slug          VARCHAR2 (350) , 
     Discount      NUMBER (5,2) , 
     Rating        NUMBER (4,2) 
    ) 
;

ALTER TABLE Products 
    ADD CONSTRAINT product_stock_ck 
    CHECK (StockQuantity > 0) 
;

ALTER TABLE Products 
    ADD CONSTRAINT Products_PK PRIMARY KEY ( ProductID ) ;

ALTER TABLE Cart 
    ADD CONSTRAINT Cart_Customer_FK FOREIGN KEY 
    ( 
     CustomerID
    ) 
    REFERENCES Customer 
    ( 
     CustomerID
    ) 
;

ALTER TABLE CartItems 
    ADD CONSTRAINT CartItems_Cart_FK FOREIGN KEY 
    ( 
     Cart_CartID
    ) 
    REFERENCES Cart 
    ( 
     CartID
    ) 
;

ALTER TABLE CartItems 
    ADD CONSTRAINT CartItems_Products_FK FOREIGN KEY 
    ( 
     Products_ProductID
    ) 
    REFERENCES Products 
    ( 
     ProductID
    ) 
;

ALTER TABLE ProductCategories 
    ADD CONSTRAINT ProdCat_Categories_FK FOREIGN KEY 
    ( 
     Categories_CategoryID
    ) 
    REFERENCES Categories 
    ( 
     CategoryID
    ) 
;

ALTER TABLE ProductCategories 
    ADD CONSTRAINT ProdtCat_Products_FK FOREIGN KEY 
    ( 
     Products_ProductID
    ) 
    REFERENCES Products 
    ( 
     ProductID
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             1
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
