-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-05-05 23:30:32 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Cart 
    ( 
     CartID     INTEGER  NOT NULL , 
     CreatedAt  DATE , 
     CustomerID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Cart 
    ADD CONSTRAINT Cart_PK PRIMARY KEY ( CartID ) ;

CREATE TABLE CartItems 
    ( 
     CartItemID INTEGER  NOT NULL , 
     Price      NUMBER (10,2)  NOT NULL , 
     CartID     INTEGER  NOT NULL , 
     ProductID  INTEGER  NOT NULL 
    ) 
;

ALTER TABLE CartItems 
    ADD CONSTRAINT CartItems_PK PRIMARY KEY ( CartItemID ) ;

CREATE TABLE Categories 
    ( 
     CategoryID  INTEGER  NOT NULL , 
     Name        NVARCHAR2 (100)  NOT NULL , 
     Description NVARCHAR2 (250) 
    ) 
;

ALTER TABLE Categories 
    ADD CONSTRAINT Categories_PK PRIMARY KEY ( CategoryID ) ;

CREATE TABLE Customer 
    ( 
     CustomerID       INTEGER  NOT NULL , 
     FirstName        NVARCHAR2 (50)  NOT NULL , 
     LastName         NVARCHAR2 (50)  NOT NULL , 
     Email            VARCHAR2 (150)  NOT NULL , 
     Password         VARCHAR2 (100)  NOT NULL , 
     PhoneNumber      VARCHAR2 (20) , 
     RegistrationDate DATE 
    ) 
;

ALTER TABLE Customer 
    ADD CONSTRAINT Customer_PK PRIMARY KEY ( CustomerID ) ;

CREATE TABLE ProductCategories 
    ( 
     ProductID  INTEGER  NOT NULL , 
     CategoryID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE ProductCategories 
    ADD CONSTRAINT ProductCategory_PK PRIMARY KEY ( ProductID, CategoryID ) ;

CREATE TABLE Products 
    ( 
     ProductID     INTEGER  NOT NULL , 
     Name          NVARCHAR2 (250)  NOT NULL , 
     Description   NVARCHAR2 (500) , 
     Price         NUMBER (10,2)  NOT NULL , 
     StockQuantity INTEGER  NOT NULL , 
     ImageUrl      VARCHAR2 (500) , 
     Slug          VARCHAR2 (350) , 
     Discount      NUMBER (5,2) , 
     Rating        NUMBER (4,2) 
    ) 
;

ALTER TABLE Products 
    ADD CONSTRAINT product_stock_ck 
    CHECK (StockQuantity > 0) 
;

ALTER TABLE Products 
    ADD CONSTRAINT Products_PK PRIMARY KEY ( ProductID ) ;

ALTER TABLE Cart 
    ADD CONSTRAINT Cart_Customer_FK FOREIGN KEY 
    ( 
     CustomerID
    ) 
    REFERENCES Customer 
    ( 
     CustomerID
    ) 
;

ALTER TABLE CartItems 
    ADD CONSTRAINT CartItems_Cart_FK FOREIGN KEY 
    ( 
     CartID
    ) 
    REFERENCES Cart 
    ( 
     CartID
    ) 
;

ALTER TABLE CartItems 
    ADD CONSTRAINT CartItems_Products_FK FOREIGN KEY 
    ( 
     ProductID
    ) 
    REFERENCES Products 
    ( 
     ProductID
    ) 
;

ALTER TABLE ProductCategories 
    ADD CONSTRAINT Categories_FK FOREIGN KEY 
    ( 
     CategoryID
    ) 
    REFERENCES Categories 
    ( 
     CategoryID
    ) 
;

ALTER TABLE ProductCategories 
    ADD CONSTRAINT Products_FK FOREIGN KEY 
    ( 
     ProductID
    ) 
    REFERENCES Products 
    ( 
     ProductID
    ) 
;

CREATE SEQUENCE Cart_CartID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Cart_CartID_TRG 
BEFORE INSERT ON Cart 
FOR EACH ROW 
WHEN (NEW.CartID IS NULL) 
BEGIN 
    :NEW.CartID := Cart_CartID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE CartItems_CartItemID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER CartItems_CartItemID_TRG 
BEFORE INSERT ON CartItems 
FOR EACH ROW 
WHEN (NEW.CartItemID IS NULL) 
BEGIN 
    :NEW.CartItemID := CartItems_CartItemID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE Categories_CategoryID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Categories_CategoryID_TRG 
BEFORE INSERT ON Categories 
FOR EACH ROW 
WHEN (NEW.CategoryID IS NULL) 
BEGIN 
    :NEW.CategoryID := Categories_CategoryID_SEQ.NEXTVAL; 
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           3
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          3
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
