-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-05-03 23:53:00 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Categories 
    ( 
     CategoryID  INTEGER  NOT NULL , 
     Name        NVARCHAR2 (100)  NOT NULL , 
     Description NVARCHAR2 (250) 
    ) 
;

ALTER TABLE Categories 
    ADD CONSTRAINT Categories_PK PRIMARY KEY ( CategoryID ) ;

CREATE TABLE ProductCategories 
    ( 
     ProductID  INTEGER  NOT NULL , 
     CategoryID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE ProductCategories 
    ADD CONSTRAINT ProductCategory_PK PRIMARY KEY ( ProductID, CategoryID ) ;

CREATE TABLE Products 
    ( 
     ProductID     INTEGER  NOT NULL , 
     Name          NVARCHAR2 (250)  NOT NULL , 
     Description   NVARCHAR2 (500) , 
     Price         NUMBER (10,2)  NOT NULL , 
     StockQuantity INTEGER  NOT NULL , 
     ImageUrl      VARCHAR2 (500) , 
     Slug          VARCHAR2 (350) , 
     Discount      NUMBER (5,2) , 
     Rating        NUMBER (4,2) 
    ) 
;

ALTER TABLE Products 
    ADD CONSTRAINT product_stock_ck 
    CHECK (StockQuantity > 0) 
;

ALTER TABLE Products 
    ADD CONSTRAINT Products_PK PRIMARY KEY ( ProductID ) ;

ALTER TABLE ProductCategories 
    ADD CONSTRAINT Categories_FK FOREIGN KEY 
    ( 
     CategoryID
    ) 
    REFERENCES Categories 
    ( 
     CategoryID
    ) 
;

ALTER TABLE ProductCategories 
    ADD CONSTRAINT Products_FK FOREIGN KEY 
    ( 
     ProductID
    ) 
    REFERENCES Products 
    ( 
     ProductID
    ) 
;

CREATE SEQUENCE Categories_CategoryID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Categories_CategoryID_TRG 
BEFORE INSERT ON Categories 
FOR EACH ROW 
WHEN (NEW.CategoryID IS NULL) 
BEGIN 
    :NEW.CategoryID := Categories_CategoryID_SEQ.NEXTVAL; 
END;
/

 